# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 02007a755c66215a9993a160c7370eda67cc914d0165d37b05772579034bf53d91d1387fc17858765b59ffcd0f87a4836e92bb1211bd46d8b39e1b4413830eae

test:
  secret_key_base: c0bf61a652eedd6eb1b7e7a17836b053707e5904b76992090e8b28febadfd3f86297d9427da71a3294e7de80f638e584da85788469fd7d8a9239356bc79aa822

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
