# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6fb0f316a65d5114ab0aade255c8e11ab74d5685c1752dad33338d4593f9e3a86449edb3fe327b3fa4eb7bad6f53ba6a5bea3b0984a14ae73bffe0c87924c3ad

test:
  secret_key_base: 44fc56bd9553d1da7368cda326da422f578cc2d05ef2303063a6773eb0a7ca95c8364c5110f6424e6c150a9b7b04ed1fb9f165a566a5afb07cb8c57cec971495

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
